package com.jxq.dao;

import com.jxq.dataobject.UserDO;

public interface UserDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Wed May 15 17:05:51 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Wed May 15 17:05:51 CST 2019
     */
    int insert(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Wed May 15 17:05:51 CST 2019
     */
    int insertSelective(UserDO record);

    /**
     * 根据用id，查询用户信息
     * @param id
     * @return
     */
    UserDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Wed May 15 17:05:51 CST 2019
     */


    //根据电话号码取得用户对象
    UserDO selectByTelphone(String telphone);

    int updateByPrimaryKeySelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Wed May 15 17:05:51 CST 2019
     */
    int updateByPrimaryKey(UserDO record);
}