#配置server的端口
server:
  port: 8090
#配置mapper文件的位置
mybatis:
  mapper-locations: classpath:mapping/*.xml
#spring 整合mybatis
#1整合数据库
spring:
  datasource:
    name: miaosha
    url: jdbc:mysql://127.0.0.1:3306/miaosha
    username: root
    password: root
#使用数据源
#使用druid的数据源，驱动
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver